apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal
spec:
 replicas: 2
 selector:
   matchLabels:
      app: job-portal
 template:
   metadata:
     labels:
       app: job-portal
   spec:
     containers:
        - name: job-portal
          image: didin8080/job-portal
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
