apiVersion: v1
kind: Service
metadata:
  name: job-portalservice
spec:
  type: LoadBalancer
  selector:
    app: job-portal
  ports:
   - name: metrics
     protocol: TCP
     port: 80
     targetPort: 4000
